export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILURE = 'USERS_FAILURE';

export const DRINKS_LOADING = 'DRINKS_LOADING';
export const DRINKS_FAILURE = 'DRINKS_FAILURE';
export const ADD_DRINKS = 'ADD_DRINKS';
export const ADD_NEW_DRINK = 'ADD_NEW_DRINK';


export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';

export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_FAILURE = 'MEMBERS_FAILURE';
export const ADD_MEMBERS = 'ADD_MEMBERS';
export const ADD_NEW_MEMBER = 'ADD_NEW_MEMBER';

export const ADD_FEEDBACKS = 'ADD_FEEDBACS';
export const FEEDBACKS_LOADING = 'FEEDBACKS_LOADING';
export const FEEDBACKS_FAILURE = 'FEEDBACKS_FAILURE';